version: '3'
services:
  backend:
    build:
      args:
        user: www-data
        uid: 33
      context: .
    restart: always
    container_name: backend_app
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: VSCODE
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'abc.app.br:127.0.0.1'
    volumes:
      - ./app/backend/:/var/www/
      - ./docker/php/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
    ports:
      - 80:80
    networks:
      - netLocal
    depends_on:
      - sonarqube

  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - netLocal
    environment:
      - SONARQUBE_JDBC_URL=jdbc:sqlite:/opt/sonarqube/data/sonar.db
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp

networks:
  netLocal:
    driver: bridge

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  sonarqube_temp:
