version: '3'
services:
  backend:
    build:
      args:
        user: www-data
        uid: 33
      context: .
    restart: always
    container_name: backend_app
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: VSCODE
    extra_hosts:
      - 'host.docker.internal:host-gateway'
      - 'abc.app.br:127.0.0.1'
    volumes:
      - ./app/backend/:/var/www/
      - ./docker/php/config/timezone.ini:/usr/local/etc/php/conf.d/timezone.ini
      - ./docker/php/config/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/config/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/conf.d/
      # - ./app/frontend/dist/spa:/usr/share/nginx/html
    ports:
      - 80:80
    networks:
      - netLocal

networks:
  netLocal:
    driver: bridge
